name: Generate Pac-Man contribution graph

on:
  schedule:
    - cron: "0 0 * * *"     # daily
  workflow_dispatch:        # allow manual run

permissions:
  contents: write           # needed to push to output branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate pacman SVGs
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          # Optional: theme=githubDark, format=svg, speed=medium, sound=off

      # Push dist/ to the output branch (creates/updates `output` branch)
      - name: Publish SVGs to output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
