name: Generate contribution snake

on:
  schedule:
    - cron: "0 0 * * *"      # run daily
  workflow_dispatch:         # allow manual run
  push:
    branches: [ main ]       # optional: rebuild on README edits

permissions:
  contents: write            # REQUIRED to push to output branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake SVGs
        uses: Platane/snk@v3
        with:
          github_user_name: heithemdev
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg

      - name: Push to output branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -B output
          mkdir -p output
          cp dist/github-contribution-grid-snake*.svg output/
          git add output/*.svg
          git commit -m "Update snake SVGs"
          git push -f origin output
